package com.dao;

import com.dao.base.BaseDaoImpl;
import com.model.Company;
import org.springframework.stereotype.Component;

@Component("companyMapper")
public class CompanyMapper extends BaseDaoImpl {

    public String getNameSpace(){return "Company";}

    //    int deleteByPrimaryKey(Integer id);


    public long insert(Company record){
        return (Long)getSqlMapClientTemplate().insert(getNameSpace()+"."+"insert",record);
    }


//    int insertSelective(Company record);


    public Company selectByPrimaryKey(Integer id){
        return (Company) getSqlMapClientTemplate().queryForObject(getNameSpace()+"."+"selectByPrimaryKey",id);
    }



//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table company
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(Company record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table company
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(Company record);
}