package com.model;

import java.util.Date;

public class CatEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_event.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_event.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_event.action_date
     *
     * @mbg.generated
     */
    private Date actionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_event.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_event.event_type
     *
     * @mbg.generated
     */
    private String eventType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_event.id
     *
     * @return the value of cat_event.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_event.id
     *
     * @param id the value for cat_event.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_event.content
     *
     * @return the value of cat_event.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_event.content
     *
     * @param content the value for cat_event.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_event.action_date
     *
     * @return the value of cat_event.action_date
     *
     * @mbg.generated
     */
    public Date getActionDate() {
        return actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_event.action_date
     *
     * @param actionDate the value for cat_event.action_date
     *
     * @mbg.generated
     */
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_event.status
     *
     * @return the value of cat_event.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_event.status
     *
     * @param status the value for cat_event.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_event.event_type
     *
     * @return the value of cat_event.event_type
     *
     * @mbg.generated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_event.event_type
     *
     * @param eventType the value for cat_event.event_type
     *
     * @mbg.generated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
}