package com.model;

import java.math.BigDecimal;

public class CompanyStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.jd_count
     *
     * @mbg.generated
     */
    private Integer jdCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.candidate_count
     *
     * @mbg.generated
     */
    private Integer candidateCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.offer_count
     *
     * @mbg.generated
     */
    private Integer offerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.paid_amount
     *
     * @mbg.generated
     */
    private BigDecimal paidAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_statistics.charge_amount
     *
     * @mbg.generated
     */
    private BigDecimal chargeAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.id
     *
     * @return the value of company_statistics.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.id
     *
     * @param id the value for company_statistics.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.company_id
     *
     * @return the value of company_statistics.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.company_id
     *
     * @param companyId the value for company_statistics.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.jd_count
     *
     * @return the value of company_statistics.jd_count
     *
     * @mbg.generated
     */
    public Integer getJdCount() {
        return jdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.jd_count
     *
     * @param jdCount the value for company_statistics.jd_count
     *
     * @mbg.generated
     */
    public void setJdCount(Integer jdCount) {
        this.jdCount = jdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.candidate_count
     *
     * @return the value of company_statistics.candidate_count
     *
     * @mbg.generated
     */
    public Integer getCandidateCount() {
        return candidateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.candidate_count
     *
     * @param candidateCount the value for company_statistics.candidate_count
     *
     * @mbg.generated
     */
    public void setCandidateCount(Integer candidateCount) {
        this.candidateCount = candidateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.offer_count
     *
     * @return the value of company_statistics.offer_count
     *
     * @mbg.generated
     */
    public Integer getOfferCount() {
        return offerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.offer_count
     *
     * @param offerCount the value for company_statistics.offer_count
     *
     * @mbg.generated
     */
    public void setOfferCount(Integer offerCount) {
        this.offerCount = offerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.paid_amount
     *
     * @return the value of company_statistics.paid_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.paid_amount
     *
     * @param paidAmount the value for company_statistics.paid_amount
     *
     * @mbg.generated
     */
    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.version
     *
     * @return the value of company_statistics.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.version
     *
     * @param version the value for company_statistics.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.charge_amount
     *
     * @return the value of company_statistics.charge_amount
     *
     * @mbg.generated
     */
    public BigDecimal getChargeAmount() {
        return chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.charge_amount
     *
     * @param chargeAmount the value for company_statistics.charge_amount
     *
     * @mbg.generated
     */
    public void setChargeAmount(BigDecimal chargeAmount) {
        this.chargeAmount = chargeAmount;
    }
}