package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class CompanyAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.avaliable_amount
     *
     * @mbg.generated
     */
    private BigDecimal avaliableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.is_valid
     *
     * @mbg.generated
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.account_type
     *
     * @mbg.generated
     */
    private String accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.id
     *
     * @return the value of company_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.id
     *
     * @param id the value for company_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.company_id
     *
     * @return the value of company_account.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.company_id
     *
     * @param companyId the value for company_account.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.amount
     *
     * @return the value of company_account.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.amount
     *
     * @param amount the value for company_account.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.avaliable_amount
     *
     * @return the value of company_account.avaliable_amount
     *
     * @mbg.generated
     */
    public BigDecimal getAvaliableAmount() {
        return avaliableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.avaliable_amount
     *
     * @param avaliableAmount the value for company_account.avaliable_amount
     *
     * @mbg.generated
     */
    public void setAvaliableAmount(BigDecimal avaliableAmount) {
        this.avaliableAmount = avaliableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.created_at
     *
     * @return the value of company_account.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.created_at
     *
     * @param createdAt the value for company_account.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.is_valid
     *
     * @return the value of company_account.is_valid
     *
     * @mbg.generated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.is_valid
     *
     * @param isValid the value for company_account.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.account_type
     *
     * @return the value of company_account.account_type
     *
     * @mbg.generated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.account_type
     *
     * @param accountType the value for company_account.account_type
     *
     * @mbg.generated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account.version
     *
     * @return the value of company_account.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account.version
     *
     * @param version the value for company_account.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }
}