package com.model;

import java.util.Date;

public class CompanyManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.dc
     *
     * @mbg.generated
     */
    private String dc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.is_header
     *
     * @mbg.generated
     */
    private String isHeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_manager.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.id
     *
     * @return the value of company_manager.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.id
     *
     * @param id the value for company_manager.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.company_id
     *
     * @return the value of company_manager.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.company_id
     *
     * @param companyId the value for company_manager.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.name
     *
     * @return the value of company_manager.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.name
     *
     * @param name the value for company_manager.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.title
     *
     * @return the value of company_manager.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.title
     *
     * @param title the value for company_manager.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.dc
     *
     * @return the value of company_manager.dc
     *
     * @mbg.generated
     */
    public String getDc() {
        return dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.dc
     *
     * @param dc the value for company_manager.dc
     *
     * @mbg.generated
     */
    public void setDc(String dc) {
        this.dc = dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.is_header
     *
     * @return the value of company_manager.is_header
     *
     * @mbg.generated
     */
    public String getIsHeader() {
        return isHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.is_header
     *
     * @param isHeader the value for company_manager.is_header
     *
     * @mbg.generated
     */
    public void setIsHeader(String isHeader) {
        this.isHeader = isHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.pic_url
     *
     * @return the value of company_manager.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.pic_url
     *
     * @param picUrl the value for company_manager.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_manager.created_at
     *
     * @return the value of company_manager.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_manager.created_at
     *
     * @param createdAt the value for company_manager.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}