package com.model;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

public class Company {

    public Company() {
    }

    public Company(String userName, String password, String tel) {
        this.userName = userName;
        this.password = password;
        this.tel = tel;
        this.createdAt=new Date();
        this.discount=new BigDecimal(BigInteger.ONE);
        this.isNewer="1";
        this.isValid="0";
        this.isVerified="0";
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.display_name
     *
     * @mbg.generated
     */
    @NotBlank(message = "公司名称不能为空！")
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.staff_scope
     *
     * @mbg.generated
     */
    private Integer staffScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.biz_catalog
     *
     * @mbg.generated
     */
    private String bizCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.institutional_investor
     *
     * @mbg.generated
     */
    private String institutionalInvestor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.dc
     *
     * @mbg.generated
     */
    private String dc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_verified
     *
     * @mbg.generated
     */
    private String isVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.verified_time
     *
     * @mbg.generated
     */
    private Date verifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_newer
     *
     * @mbg.generated
     */
    private String isNewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.tel
     *
     * @mbg.generated
     */
    @NotBlank(message = "公司联系电话不能为空！")
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.mail
     *
     * @mbg.generated
     */
    @NotBlank(message = "公司邮箱不能为空！")
    @Email(message = "公司邮箱格式错误！")
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.logo_url
     *
     * @mbg.generated
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.discount
     *
     * @mbg.generated
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_valid
     *
     * @mbg.generated
     */
    private String isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.display_name
     *
     * @return the value of company.display_name
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.display_name
     *
     * @param displayName the value for company.display_name
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.user_name
     *
     * @return the value of company.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.user_name
     *
     * @param userName the value for company.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.password
     *
     * @return the value of company.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.password
     *
     * @param password the value for company.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.staff_scope
     *
     * @return the value of company.staff_scope
     *
     * @mbg.generated
     */
    public Integer getStaffScope() {
        return staffScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.staff_scope
     *
     * @param staffScope the value for company.staff_scope
     *
     * @mbg.generated
     */
    public void setStaffScope(Integer staffScope) {
        this.staffScope = staffScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.biz_catalog
     *
     * @return the value of company.biz_catalog
     *
     * @mbg.generated
     */
    public String getBizCatalog() {
        return bizCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.biz_catalog
     *
     * @param bizCatalog the value for company.biz_catalog
     *
     * @mbg.generated
     */
    public void setBizCatalog(String bizCatalog) {
        this.bizCatalog = bizCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.institutional_investor
     *
     * @return the value of company.institutional_investor
     *
     * @mbg.generated
     */
    public String getInstitutionalInvestor() {
        return institutionalInvestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.institutional_investor
     *
     * @param institutionalInvestor the value for company.institutional_investor
     *
     * @mbg.generated
     */
    public void setInstitutionalInvestor(String institutionalInvestor) {
        this.institutionalInvestor = institutionalInvestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.dc
     *
     * @return the value of company.dc
     *
     * @mbg.generated
     */
    public String getDc() {
        return dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.dc
     *
     * @param dc the value for company.dc
     *
     * @mbg.generated
     */
    public void setDc(String dc) {
        this.dc = dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_verified
     *
     * @return the value of company.is_verified
     *
     * @mbg.generated
     */
    public String getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_verified
     *
     * @param isVerified the value for company.is_verified
     *
     * @mbg.generated
     */
    public void setIsVerified(String isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.verified_time
     *
     * @return the value of company.verified_time
     *
     * @mbg.generated
     */
    public Date getVerifiedTime() {
        return verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.verified_time
     *
     * @param verifiedTime the value for company.verified_time
     *
     * @mbg.generated
     */
    public void setVerifiedTime(Date verifiedTime) {
        this.verifiedTime = verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_newer
     *
     * @return the value of company.is_newer
     *
     * @mbg.generated
     */
    public String getIsNewer() {
        return isNewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_newer
     *
     * @param isNewer the value for company.is_newer
     *
     * @mbg.generated
     */
    public void setIsNewer(String isNewer) {
        this.isNewer = isNewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.created_at
     *
     * @return the value of company.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.created_at
     *
     * @param createdAt the value for company.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.tel
     *
     * @return the value of company.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.tel
     *
     * @param tel the value for company.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.mail
     *
     * @return the value of company.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.mail
     *
     * @param mail the value for company.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.logo_url
     *
     * @return the value of company.logo_url
     *
     * @mbg.generated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.logo_url
     *
     * @param logoUrl the value for company.logo_url
     *
     * @mbg.generated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.discount
     *
     * @return the value of company.discount
     *
     * @mbg.generated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.discount
     *
     * @param discount the value for company.discount
     *
     * @mbg.generated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.remark
     *
     * @return the value of company.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.remark
     *
     * @param remark the value for company.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_valid
     *
     * @return the value of company.is_valid
     *
     * @mbg.generated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_valid
     *
     * @param isValid the value for company.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }
}