package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class CompanyAccountTransaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.series_number
     *
     * @mbg.generated
     */
    private String seriesNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.direction
     *
     * @mbg.generated
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.pre_amount
     *
     * @mbg.generated
     */
    private BigDecimal preAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.post_amount
     *
     * @mbg.generated
     */
    private BigDecimal postAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.action_date
     *
     * @mbg.generated
     */
    private Date actionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.account_type
     *
     * @mbg.generated
     */
    private String accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_account_transaction.biz_type
     *
     * @mbg.generated
     */
    private String bizType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.id
     *
     * @return the value of company_account_transaction.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.id
     *
     * @param id the value for company_account_transaction.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.company_id
     *
     * @return the value of company_account_transaction.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.company_id
     *
     * @param companyId the value for company_account_transaction.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.series_number
     *
     * @return the value of company_account_transaction.series_number
     *
     * @mbg.generated
     */
    public String getSeriesNumber() {
        return seriesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.series_number
     *
     * @param seriesNumber the value for company_account_transaction.series_number
     *
     * @mbg.generated
     */
    public void setSeriesNumber(String seriesNumber) {
        this.seriesNumber = seriesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.direction
     *
     * @return the value of company_account_transaction.direction
     *
     * @mbg.generated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.direction
     *
     * @param direction the value for company_account_transaction.direction
     *
     * @mbg.generated
     */
    public void setDirection(String direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.amount
     *
     * @return the value of company_account_transaction.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.amount
     *
     * @param amount the value for company_account_transaction.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.pre_amount
     *
     * @return the value of company_account_transaction.pre_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPreAmount() {
        return preAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.pre_amount
     *
     * @param preAmount the value for company_account_transaction.pre_amount
     *
     * @mbg.generated
     */
    public void setPreAmount(BigDecimal preAmount) {
        this.preAmount = preAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.post_amount
     *
     * @return the value of company_account_transaction.post_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPostAmount() {
        return postAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.post_amount
     *
     * @param postAmount the value for company_account_transaction.post_amount
     *
     * @mbg.generated
     */
    public void setPostAmount(BigDecimal postAmount) {
        this.postAmount = postAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.action_date
     *
     * @return the value of company_account_transaction.action_date
     *
     * @mbg.generated
     */
    public Date getActionDate() {
        return actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.action_date
     *
     * @param actionDate the value for company_account_transaction.action_date
     *
     * @mbg.generated
     */
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.remark
     *
     * @return the value of company_account_transaction.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.remark
     *
     * @param remark the value for company_account_transaction.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.account_type
     *
     * @return the value of company_account_transaction.account_type
     *
     * @mbg.generated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.account_type
     *
     * @param accountType the value for company_account_transaction.account_type
     *
     * @mbg.generated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.account_id
     *
     * @return the value of company_account_transaction.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.account_id
     *
     * @param accountId the value for company_account_transaction.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_account_transaction.biz_type
     *
     * @return the value of company_account_transaction.biz_type
     *
     * @mbg.generated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_account_transaction.biz_type
     *
     * @param bizType the value for company_account_transaction.biz_type
     *
     * @mbg.generated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }
}