package com.model;

import java.util.Date;

public class HunterCompanyQualification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company_qualification.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company_qualification.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company_qualification.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company_qualification.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company_qualification.hunter_company_id
     *
     * @mbg.generated
     */
    private Integer hunterCompanyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company_qualification.id
     *
     * @return the value of hunter_company_qualification.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company_qualification.id
     *
     * @param id the value for hunter_company_qualification.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company_qualification.name
     *
     * @return the value of hunter_company_qualification.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company_qualification.name
     *
     * @param name the value for hunter_company_qualification.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company_qualification.pic_url
     *
     * @return the value of hunter_company_qualification.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company_qualification.pic_url
     *
     * @param picUrl the value for hunter_company_qualification.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company_qualification.created_at
     *
     * @return the value of hunter_company_qualification.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company_qualification.created_at
     *
     * @param createdAt the value for hunter_company_qualification.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company_qualification.hunter_company_id
     *
     * @return the value of hunter_company_qualification.hunter_company_id
     *
     * @mbg.generated
     */
    public Integer getHunterCompanyId() {
        return hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company_qualification.hunter_company_id
     *
     * @param hunterCompanyId the value for hunter_company_qualification.hunter_company_id
     *
     * @mbg.generated
     */
    public void setHunterCompanyId(Integer hunterCompanyId) {
        this.hunterCompanyId = hunterCompanyId;
    }
}