package com.model;

import java.util.Date;

public class HunterCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.display_name
     *
     * @mbg.generated
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.dc
     *
     * @mbg.generated
     */
    private String dc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.is_verified
     *
     * @mbg.generated
     */
    private String isVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.verified_time
     *
     * @mbg.generated
     */
    private Date verifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.is_valid
     *
     * @mbg.generated
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.is_newer
     *
     * @mbg.generated
     */
    private String isNewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.logo_url
     *
     * @mbg.generated
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_company.is_qualification_complete
     *
     * @mbg.generated
     */
    private String isQualificationComplete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.id
     *
     * @return the value of hunter_company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.id
     *
     * @param id the value for hunter_company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.display_name
     *
     * @return the value of hunter_company.display_name
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.display_name
     *
     * @param displayName the value for hunter_company.display_name
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.user_name
     *
     * @return the value of hunter_company.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.user_name
     *
     * @param userName the value for hunter_company.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.password
     *
     * @return the value of hunter_company.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.password
     *
     * @param password the value for hunter_company.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.dc
     *
     * @return the value of hunter_company.dc
     *
     * @mbg.generated
     */
    public String getDc() {
        return dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.dc
     *
     * @param dc the value for hunter_company.dc
     *
     * @mbg.generated
     */
    public void setDc(String dc) {
        this.dc = dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.is_verified
     *
     * @return the value of hunter_company.is_verified
     *
     * @mbg.generated
     */
    public String getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.is_verified
     *
     * @param isVerified the value for hunter_company.is_verified
     *
     * @mbg.generated
     */
    public void setIsVerified(String isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.verified_time
     *
     * @return the value of hunter_company.verified_time
     *
     * @mbg.generated
     */
    public Date getVerifiedTime() {
        return verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.verified_time
     *
     * @param verifiedTime the value for hunter_company.verified_time
     *
     * @mbg.generated
     */
    public void setVerifiedTime(Date verifiedTime) {
        this.verifiedTime = verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.remark
     *
     * @return the value of hunter_company.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.remark
     *
     * @param remark the value for hunter_company.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.is_valid
     *
     * @return the value of hunter_company.is_valid
     *
     * @mbg.generated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.is_valid
     *
     * @param isValid the value for hunter_company.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.is_newer
     *
     * @return the value of hunter_company.is_newer
     *
     * @mbg.generated
     */
    public String getIsNewer() {
        return isNewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.is_newer
     *
     * @param isNewer the value for hunter_company.is_newer
     *
     * @mbg.generated
     */
    public void setIsNewer(String isNewer) {
        this.isNewer = isNewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.created_at
     *
     * @return the value of hunter_company.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.created_at
     *
     * @param createdAt the value for hunter_company.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.tel
     *
     * @return the value of hunter_company.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.tel
     *
     * @param tel the value for hunter_company.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.mail
     *
     * @return the value of hunter_company.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.mail
     *
     * @param mail the value for hunter_company.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.logo_url
     *
     * @return the value of hunter_company.logo_url
     *
     * @mbg.generated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.logo_url
     *
     * @param logoUrl the value for hunter_company.logo_url
     *
     * @mbg.generated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_company.is_qualification_complete
     *
     * @return the value of hunter_company.is_qualification_complete
     *
     * @mbg.generated
     */
    public String getIsQualificationComplete() {
        return isQualificationComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_company.is_qualification_complete
     *
     * @param isQualificationComplete the value for hunter_company.is_qualification_complete
     *
     * @mbg.generated
     */
    public void setIsQualificationComplete(String isQualificationComplete) {
        this.isQualificationComplete = isQualificationComplete;
    }
}