package com.model;

import java.util.Date;

public class Hunter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.hunter_company_id
     *
     * @mbg.generated
     */
    private Integer hunterCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.identification_card
     *
     * @mbg.generated
     */
    private String identificationCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.workyear
     *
     * @mbg.generated
     */
    private Integer workyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.is_verified
     *
     * @mbg.generated
     */
    private String isVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.verified_time
     *
     * @mbg.generated
     */
    private Date verifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.remar
     *
     * @mbg.generated
     */
    private String remar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.is_valid
     *
     * @mbg.generated
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.is_newer
     *
     * @mbg.generated
     */
    private String isNewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.login_time
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.star_level
     *
     * @mbg.generated
     */
    private String starLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.active_level
     *
     * @mbg.generated
     */
    private String activeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter.display_name
     *
     * @mbg.generated
     */
    private String displayName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.id
     *
     * @return the value of hunter.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.id
     *
     * @param id the value for hunter.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.hunter_company_id
     *
     * @return the value of hunter.hunter_company_id
     *
     * @mbg.generated
     */
    public Integer getHunterCompanyId() {
        return hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.hunter_company_id
     *
     * @param hunterCompanyId the value for hunter.hunter_company_id
     *
     * @mbg.generated
     */
    public void setHunterCompanyId(Integer hunterCompanyId) {
        this.hunterCompanyId = hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.user_name
     *
     * @return the value of hunter.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.user_name
     *
     * @param userName the value for hunter.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.password
     *
     * @return the value of hunter.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.password
     *
     * @param password the value for hunter.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.sex
     *
     * @return the value of hunter.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.sex
     *
     * @param sex the value for hunter.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.identification_card
     *
     * @return the value of hunter.identification_card
     *
     * @mbg.generated
     */
    public String getIdentificationCard() {
        return identificationCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.identification_card
     *
     * @param identificationCard the value for hunter.identification_card
     *
     * @mbg.generated
     */
    public void setIdentificationCard(String identificationCard) {
        this.identificationCard = identificationCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.age
     *
     * @return the value of hunter.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.age
     *
     * @param age the value for hunter.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.workyear
     *
     * @return the value of hunter.workyear
     *
     * @mbg.generated
     */
    public Integer getWorkyear() {
        return workyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.workyear
     *
     * @param workyear the value for hunter.workyear
     *
     * @mbg.generated
     */
    public void setWorkyear(Integer workyear) {
        this.workyear = workyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.title
     *
     * @return the value of hunter.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.title
     *
     * @param title the value for hunter.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.is_verified
     *
     * @return the value of hunter.is_verified
     *
     * @mbg.generated
     */
    public String getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.is_verified
     *
     * @param isVerified the value for hunter.is_verified
     *
     * @mbg.generated
     */
    public void setIsVerified(String isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.verified_time
     *
     * @return the value of hunter.verified_time
     *
     * @mbg.generated
     */
    public Date getVerifiedTime() {
        return verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.verified_time
     *
     * @param verifiedTime the value for hunter.verified_time
     *
     * @mbg.generated
     */
    public void setVerifiedTime(Date verifiedTime) {
        this.verifiedTime = verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.remar
     *
     * @return the value of hunter.remar
     *
     * @mbg.generated
     */
    public String getRemar() {
        return remar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.remar
     *
     * @param remar the value for hunter.remar
     *
     * @mbg.generated
     */
    public void setRemar(String remar) {
        this.remar = remar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.is_valid
     *
     * @return the value of hunter.is_valid
     *
     * @mbg.generated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.is_valid
     *
     * @param isValid the value for hunter.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.is_newer
     *
     * @return the value of hunter.is_newer
     *
     * @mbg.generated
     */
    public String getIsNewer() {
        return isNewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.is_newer
     *
     * @param isNewer the value for hunter.is_newer
     *
     * @mbg.generated
     */
    public void setIsNewer(String isNewer) {
        this.isNewer = isNewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.created_at
     *
     * @return the value of hunter.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.created_at
     *
     * @param createdAt the value for hunter.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.tel
     *
     * @return the value of hunter.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.tel
     *
     * @param tel the value for hunter.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.mail
     *
     * @return the value of hunter.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.mail
     *
     * @param mail the value for hunter.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.pic_url
     *
     * @return the value of hunter.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.pic_url
     *
     * @param picUrl the value for hunter.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.login_time
     *
     * @return the value of hunter.login_time
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.login_time
     *
     * @param loginTime the value for hunter.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.star_level
     *
     * @return the value of hunter.star_level
     *
     * @mbg.generated
     */
    public String getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.star_level
     *
     * @param starLevel the value for hunter.star_level
     *
     * @mbg.generated
     */
    public void setStarLevel(String starLevel) {
        this.starLevel = starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.active_level
     *
     * @return the value of hunter.active_level
     *
     * @mbg.generated
     */
    public String getActiveLevel() {
        return activeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.active_level
     *
     * @param activeLevel the value for hunter.active_level
     *
     * @mbg.generated
     */
    public void setActiveLevel(String activeLevel) {
        this.activeLevel = activeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.status
     *
     * @return the value of hunter.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.status
     *
     * @param status the value for hunter.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter.display_name
     *
     * @return the value of hunter.display_name
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter.display_name
     *
     * @param displayName the value for hunter.display_name
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
}