package com.model;

import java.math.BigDecimal;

public class HunterStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_statistics.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_statistics.hunter_id
     *
     * @mbg.generated
     */
    private Integer hunterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_statistics.dispatch_count
     *
     * @mbg.generated
     */
    private Integer dispatchCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_statistics.onsite_rate
     *
     * @mbg.generated
     */
    private BigDecimal onsiteRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_statistics.offered_rate
     *
     * @mbg.generated
     */
    private BigDecimal offeredRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_statistics.recommend_count
     *
     * @mbg.generated
     */
    private Integer recommendCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hunter_statistics.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_statistics.id
     *
     * @return the value of hunter_statistics.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_statistics.id
     *
     * @param id the value for hunter_statistics.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_statistics.hunter_id
     *
     * @return the value of hunter_statistics.hunter_id
     *
     * @mbg.generated
     */
    public Integer getHunterId() {
        return hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_statistics.hunter_id
     *
     * @param hunterId the value for hunter_statistics.hunter_id
     *
     * @mbg.generated
     */
    public void setHunterId(Integer hunterId) {
        this.hunterId = hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_statistics.dispatch_count
     *
     * @return the value of hunter_statistics.dispatch_count
     *
     * @mbg.generated
     */
    public Integer getDispatchCount() {
        return dispatchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_statistics.dispatch_count
     *
     * @param dispatchCount the value for hunter_statistics.dispatch_count
     *
     * @mbg.generated
     */
    public void setDispatchCount(Integer dispatchCount) {
        this.dispatchCount = dispatchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_statistics.onsite_rate
     *
     * @return the value of hunter_statistics.onsite_rate
     *
     * @mbg.generated
     */
    public BigDecimal getOnsiteRate() {
        return onsiteRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_statistics.onsite_rate
     *
     * @param onsiteRate the value for hunter_statistics.onsite_rate
     *
     * @mbg.generated
     */
    public void setOnsiteRate(BigDecimal onsiteRate) {
        this.onsiteRate = onsiteRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_statistics.offered_rate
     *
     * @return the value of hunter_statistics.offered_rate
     *
     * @mbg.generated
     */
    public BigDecimal getOfferedRate() {
        return offeredRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_statistics.offered_rate
     *
     * @param offeredRate the value for hunter_statistics.offered_rate
     *
     * @mbg.generated
     */
    public void setOfferedRate(BigDecimal offeredRate) {
        this.offeredRate = offeredRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_statistics.recommend_count
     *
     * @return the value of hunter_statistics.recommend_count
     *
     * @mbg.generated
     */
    public Integer getRecommendCount() {
        return recommendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_statistics.recommend_count
     *
     * @param recommendCount the value for hunter_statistics.recommend_count
     *
     * @mbg.generated
     */
    public void setRecommendCount(Integer recommendCount) {
        this.recommendCount = recommendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hunter_statistics.version
     *
     * @return the value of hunter_statistics.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hunter_statistics.version
     *
     * @param version the value for hunter_statistics.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }
}