package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class Jd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.open_desc
     *
     * @mbg.generated
     */
    private String openDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.min_salary
     *
     * @mbg.generated
     */
    private Integer minSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.max_salary
     *
     * @mbg.generated
     */
    private Integer maxSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.required_count
     *
     * @mbg.generated
     */
    private Integer requiredCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.subordinates_count
     *
     * @mbg.generated
     */
    private Integer subordinatesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.chief
     *
     * @mbg.generated
     */
    private String chief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.province_code
     *
     * @mbg.generated
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.city_code
     *
     * @mbg.generated
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.dc
     *
     * @mbg.generated
     */
    private String dc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.required_desc
     *
     * @mbg.generated
     */
    private String requiredDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.educational_limit
     *
     * @mbg.generated
     */
    private String educationalLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.workyear_limit
     *
     * @mbg.generated
     */
    private String workyearLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.age_limit
     *
     * @mbg.generated
     */
    private String ageLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.sex_limit
     *
     * @mbg.generated
     */
    private String sexLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.language_limit
     *
     * @mbg.generated
     */
    private String languageLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.certificate_limit
     *
     * @mbg.generated
     */
    private String certificateLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.onsite_ops
     *
     * @mbg.generated
     */
    private String onsiteOps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.onsite_desc
     *
     * @mbg.generated
     */
    private String onsiteDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.onsite_remote_support
     *
     * @mbg.generated
     */
    private String onsiteRemoteSupport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.publish_at
     *
     * @mbg.generated
     */
    private Date publishAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.open_at
     *
     * @mbg.generated
     */
    private Date openAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.st_fee
     *
     * @mbg.generated
     */
    private BigDecimal stFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.advanced_st_fee
     *
     * @mbg.generated
     */
    private BigDecimal advancedStFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.deduction_st_fee
     *
     * @mbg.generated
     */
    private BigDecimal deductionStFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd.urgency
     *
     * @mbg.generated
     */
    private String urgency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.id
     *
     * @return the value of jd.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.id
     *
     * @param id the value for jd.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.company_id
     *
     * @return the value of jd.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.company_id
     *
     * @param companyId the value for jd.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.name
     *
     * @return the value of jd.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.name
     *
     * @param name the value for jd.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.open_desc
     *
     * @return the value of jd.open_desc
     *
     * @mbg.generated
     */
    public String getOpenDesc() {
        return openDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.open_desc
     *
     * @param openDesc the value for jd.open_desc
     *
     * @mbg.generated
     */
    public void setOpenDesc(String openDesc) {
        this.openDesc = openDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.min_salary
     *
     * @return the value of jd.min_salary
     *
     * @mbg.generated
     */
    public Integer getMinSalary() {
        return minSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.min_salary
     *
     * @param minSalary the value for jd.min_salary
     *
     * @mbg.generated
     */
    public void setMinSalary(Integer minSalary) {
        this.minSalary = minSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.max_salary
     *
     * @return the value of jd.max_salary
     *
     * @mbg.generated
     */
    public Integer getMaxSalary() {
        return maxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.max_salary
     *
     * @param maxSalary the value for jd.max_salary
     *
     * @mbg.generated
     */
    public void setMaxSalary(Integer maxSalary) {
        this.maxSalary = maxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.required_count
     *
     * @return the value of jd.required_count
     *
     * @mbg.generated
     */
    public Integer getRequiredCount() {
        return requiredCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.required_count
     *
     * @param requiredCount the value for jd.required_count
     *
     * @mbg.generated
     */
    public void setRequiredCount(Integer requiredCount) {
        this.requiredCount = requiredCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.subordinates_count
     *
     * @return the value of jd.subordinates_count
     *
     * @mbg.generated
     */
    public Integer getSubordinatesCount() {
        return subordinatesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.subordinates_count
     *
     * @param subordinatesCount the value for jd.subordinates_count
     *
     * @mbg.generated
     */
    public void setSubordinatesCount(Integer subordinatesCount) {
        this.subordinatesCount = subordinatesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.department
     *
     * @return the value of jd.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.department
     *
     * @param department the value for jd.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.chief
     *
     * @return the value of jd.chief
     *
     * @mbg.generated
     */
    public String getChief() {
        return chief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.chief
     *
     * @param chief the value for jd.chief
     *
     * @mbg.generated
     */
    public void setChief(String chief) {
        this.chief = chief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.province_code
     *
     * @return the value of jd.province_code
     *
     * @mbg.generated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.province_code
     *
     * @param provinceCode the value for jd.province_code
     *
     * @mbg.generated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.city_code
     *
     * @return the value of jd.city_code
     *
     * @mbg.generated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.city_code
     *
     * @param cityCode the value for jd.city_code
     *
     * @mbg.generated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.address
     *
     * @return the value of jd.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.address
     *
     * @param address the value for jd.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.dc
     *
     * @return the value of jd.dc
     *
     * @mbg.generated
     */
    public String getDc() {
        return dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.dc
     *
     * @param dc the value for jd.dc
     *
     * @mbg.generated
     */
    public void setDc(String dc) {
        this.dc = dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.required_desc
     *
     * @return the value of jd.required_desc
     *
     * @mbg.generated
     */
    public String getRequiredDesc() {
        return requiredDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.required_desc
     *
     * @param requiredDesc the value for jd.required_desc
     *
     * @mbg.generated
     */
    public void setRequiredDesc(String requiredDesc) {
        this.requiredDesc = requiredDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.educational_limit
     *
     * @return the value of jd.educational_limit
     *
     * @mbg.generated
     */
    public String getEducationalLimit() {
        return educationalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.educational_limit
     *
     * @param educationalLimit the value for jd.educational_limit
     *
     * @mbg.generated
     */
    public void setEducationalLimit(String educationalLimit) {
        this.educationalLimit = educationalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.workyear_limit
     *
     * @return the value of jd.workyear_limit
     *
     * @mbg.generated
     */
    public String getWorkyearLimit() {
        return workyearLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.workyear_limit
     *
     * @param workyearLimit the value for jd.workyear_limit
     *
     * @mbg.generated
     */
    public void setWorkyearLimit(String workyearLimit) {
        this.workyearLimit = workyearLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.age_limit
     *
     * @return the value of jd.age_limit
     *
     * @mbg.generated
     */
    public String getAgeLimit() {
        return ageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.age_limit
     *
     * @param ageLimit the value for jd.age_limit
     *
     * @mbg.generated
     */
    public void setAgeLimit(String ageLimit) {
        this.ageLimit = ageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.sex_limit
     *
     * @return the value of jd.sex_limit
     *
     * @mbg.generated
     */
    public String getSexLimit() {
        return sexLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.sex_limit
     *
     * @param sexLimit the value for jd.sex_limit
     *
     * @mbg.generated
     */
    public void setSexLimit(String sexLimit) {
        this.sexLimit = sexLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.language_limit
     *
     * @return the value of jd.language_limit
     *
     * @mbg.generated
     */
    public String getLanguageLimit() {
        return languageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.language_limit
     *
     * @param languageLimit the value for jd.language_limit
     *
     * @mbg.generated
     */
    public void setLanguageLimit(String languageLimit) {
        this.languageLimit = languageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.certificate_limit
     *
     * @return the value of jd.certificate_limit
     *
     * @mbg.generated
     */
    public String getCertificateLimit() {
        return certificateLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.certificate_limit
     *
     * @param certificateLimit the value for jd.certificate_limit
     *
     * @mbg.generated
     */
    public void setCertificateLimit(String certificateLimit) {
        this.certificateLimit = certificateLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.onsite_ops
     *
     * @return the value of jd.onsite_ops
     *
     * @mbg.generated
     */
    public String getOnsiteOps() {
        return onsiteOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.onsite_ops
     *
     * @param onsiteOps the value for jd.onsite_ops
     *
     * @mbg.generated
     */
    public void setOnsiteOps(String onsiteOps) {
        this.onsiteOps = onsiteOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.onsite_desc
     *
     * @return the value of jd.onsite_desc
     *
     * @mbg.generated
     */
    public String getOnsiteDesc() {
        return onsiteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.onsite_desc
     *
     * @param onsiteDesc the value for jd.onsite_desc
     *
     * @mbg.generated
     */
    public void setOnsiteDesc(String onsiteDesc) {
        this.onsiteDesc = onsiteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.onsite_remote_support
     *
     * @return the value of jd.onsite_remote_support
     *
     * @mbg.generated
     */
    public String getOnsiteRemoteSupport() {
        return onsiteRemoteSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.onsite_remote_support
     *
     * @param onsiteRemoteSupport the value for jd.onsite_remote_support
     *
     * @mbg.generated
     */
    public void setOnsiteRemoteSupport(String onsiteRemoteSupport) {
        this.onsiteRemoteSupport = onsiteRemoteSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.created_at
     *
     * @return the value of jd.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.created_at
     *
     * @param createdAt the value for jd.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.publish_at
     *
     * @return the value of jd.publish_at
     *
     * @mbg.generated
     */
    public Date getPublishAt() {
        return publishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.publish_at
     *
     * @param publishAt the value for jd.publish_at
     *
     * @mbg.generated
     */
    public void setPublishAt(Date publishAt) {
        this.publishAt = publishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.status
     *
     * @return the value of jd.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.status
     *
     * @param status the value for jd.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.remark
     *
     * @return the value of jd.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.remark
     *
     * @param remark the value for jd.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.code
     *
     * @return the value of jd.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.code
     *
     * @param code the value for jd.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.open_at
     *
     * @return the value of jd.open_at
     *
     * @mbg.generated
     */
    public Date getOpenAt() {
        return openAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.open_at
     *
     * @param openAt the value for jd.open_at
     *
     * @mbg.generated
     */
    public void setOpenAt(Date openAt) {
        this.openAt = openAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.st_fee
     *
     * @return the value of jd.st_fee
     *
     * @mbg.generated
     */
    public BigDecimal getStFee() {
        return stFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.st_fee
     *
     * @param stFee the value for jd.st_fee
     *
     * @mbg.generated
     */
    public void setStFee(BigDecimal stFee) {
        this.stFee = stFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.advanced_st_fee
     *
     * @return the value of jd.advanced_st_fee
     *
     * @mbg.generated
     */
    public BigDecimal getAdvancedStFee() {
        return advancedStFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.advanced_st_fee
     *
     * @param advancedStFee the value for jd.advanced_st_fee
     *
     * @mbg.generated
     */
    public void setAdvancedStFee(BigDecimal advancedStFee) {
        this.advancedStFee = advancedStFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.deduction_st_fee
     *
     * @return the value of jd.deduction_st_fee
     *
     * @mbg.generated
     */
    public BigDecimal getDeductionStFee() {
        return deductionStFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.deduction_st_fee
     *
     * @param deductionStFee the value for jd.deduction_st_fee
     *
     * @mbg.generated
     */
    public void setDeductionStFee(BigDecimal deductionStFee) {
        this.deductionStFee = deductionStFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd.urgency
     *
     * @return the value of jd.urgency
     *
     * @mbg.generated
     */
    public String getUrgency() {
        return urgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd.urgency
     *
     * @param urgency the value for jd.urgency
     *
     * @mbg.generated
     */
    public void setUrgency(String urgency) {
        this.urgency = urgency;
    }
}