package com.model;

import java.util.Date;

public class JdIndustryRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_industry_relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_industry_relation.jd_id
     *
     * @mbg.generated
     */
    private Integer jdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_industry_relation.industry_function_id
     *
     * @mbg.generated
     */
    private Integer industryFunctionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_industry_relation.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_industry_relation.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_industry_relation.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_industry_relation.id
     *
     * @return the value of jd_industry_relation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_industry_relation.id
     *
     * @param id the value for jd_industry_relation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_industry_relation.jd_id
     *
     * @return the value of jd_industry_relation.jd_id
     *
     * @mbg.generated
     */
    public Integer getJdId() {
        return jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_industry_relation.jd_id
     *
     * @param jdId the value for jd_industry_relation.jd_id
     *
     * @mbg.generated
     */
    public void setJdId(Integer jdId) {
        this.jdId = jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_industry_relation.industry_function_id
     *
     * @return the value of jd_industry_relation.industry_function_id
     *
     * @mbg.generated
     */
    public Integer getIndustryFunctionId() {
        return industryFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_industry_relation.industry_function_id
     *
     * @param industryFunctionId the value for jd_industry_relation.industry_function_id
     *
     * @mbg.generated
     */
    public void setIndustryFunctionId(Integer industryFunctionId) {
        this.industryFunctionId = industryFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_industry_relation.created_at
     *
     * @return the value of jd_industry_relation.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_industry_relation.created_at
     *
     * @param createdAt the value for jd_industry_relation.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_industry_relation.type
     *
     * @return the value of jd_industry_relation.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_industry_relation.type
     *
     * @param type the value for jd_industry_relation.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_industry_relation.name
     *
     * @return the value of jd_industry_relation.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_industry_relation.name
     *
     * @param name the value for jd_industry_relation.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }
}