package com.model;

public class JdStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.jd_id
     *
     * @mbg.generated
     */
    private Integer jdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.required_count
     *
     * @mbg.generated
     */
    private Integer requiredCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.offer_count
     *
     * @mbg.generated
     */
    private Integer offerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.onbord_count
     *
     * @mbg.generated
     */
    private Integer onbordCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.recommend_record_count
     *
     * @mbg.generated
     */
    private Integer recommendRecordCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_statistics.onsite_count
     *
     * @mbg.generated
     */
    private Integer onsiteCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.id
     *
     * @return the value of jd_statistics.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.id
     *
     * @param id the value for jd_statistics.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.jd_id
     *
     * @return the value of jd_statistics.jd_id
     *
     * @mbg.generated
     */
    public Integer getJdId() {
        return jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.jd_id
     *
     * @param jdId the value for jd_statistics.jd_id
     *
     * @mbg.generated
     */
    public void setJdId(Integer jdId) {
        this.jdId = jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.company_id
     *
     * @return the value of jd_statistics.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.company_id
     *
     * @param companyId the value for jd_statistics.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.required_count
     *
     * @return the value of jd_statistics.required_count
     *
     * @mbg.generated
     */
    public Integer getRequiredCount() {
        return requiredCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.required_count
     *
     * @param requiredCount the value for jd_statistics.required_count
     *
     * @mbg.generated
     */
    public void setRequiredCount(Integer requiredCount) {
        this.requiredCount = requiredCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.offer_count
     *
     * @return the value of jd_statistics.offer_count
     *
     * @mbg.generated
     */
    public Integer getOfferCount() {
        return offerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.offer_count
     *
     * @param offerCount the value for jd_statistics.offer_count
     *
     * @mbg.generated
     */
    public void setOfferCount(Integer offerCount) {
        this.offerCount = offerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.onbord_count
     *
     * @return the value of jd_statistics.onbord_count
     *
     * @mbg.generated
     */
    public Integer getOnbordCount() {
        return onbordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.onbord_count
     *
     * @param onbordCount the value for jd_statistics.onbord_count
     *
     * @mbg.generated
     */
    public void setOnbordCount(Integer onbordCount) {
        this.onbordCount = onbordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.version
     *
     * @return the value of jd_statistics.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.version
     *
     * @param version the value for jd_statistics.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.recommend_record_count
     *
     * @return the value of jd_statistics.recommend_record_count
     *
     * @mbg.generated
     */
    public Integer getRecommendRecordCount() {
        return recommendRecordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.recommend_record_count
     *
     * @param recommendRecordCount the value for jd_statistics.recommend_record_count
     *
     * @mbg.generated
     */
    public void setRecommendRecordCount(Integer recommendRecordCount) {
        this.recommendRecordCount = recommendRecordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_statistics.onsite_count
     *
     * @return the value of jd_statistics.onsite_count
     *
     * @mbg.generated
     */
    public Integer getOnsiteCount() {
        return onsiteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_statistics.onsite_count
     *
     * @param onsiteCount the value for jd_statistics.onsite_count
     *
     * @mbg.generated
     */
    public void setOnsiteCount(Integer onsiteCount) {
        this.onsiteCount = onsiteCount;
    }
}