package com.model;

import java.util.Date;

public class MessageRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_type
     *
     * @mbg.generated
     */
    private String messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.user_type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.action_date
     *
     * @mbg.generated
     */
    private Date actionDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.id
     *
     * @return the value of message_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.id
     *
     * @param id the value for message_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.content
     *
     * @return the value of message_record.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.content
     *
     * @param content the value for message_record.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.tel
     *
     * @return the value of message_record.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.tel
     *
     * @param tel the value for message_record.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_type
     *
     * @return the value of message_record.message_type
     *
     * @mbg.generated
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_type
     *
     * @param messageType the value for message_record.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.user_id
     *
     * @return the value of message_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.user_id
     *
     * @param userId the value for message_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.user_type
     *
     * @return the value of message_record.user_type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.user_type
     *
     * @param userType the value for message_record.user_type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.remark
     *
     * @return the value of message_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.remark
     *
     * @param remark the value for message_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.action_date
     *
     * @return the value of message_record.action_date
     *
     * @mbg.generated
     */
    public Date getActionDate() {
        return actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.action_date
     *
     * @param actionDate the value for message_record.action_date
     *
     * @mbg.generated
     */
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }
}