package com.model;

public class MessageStrategy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_strategy.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_strategy.limit_date
     *
     * @mbg.generated
     */
    private String limitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_strategy.total_count
     *
     * @mbg.generated
     */
    private Integer totalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_strategy.sended_count
     *
     * @mbg.generated
     */
    private Integer sendedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_strategy.message_type
     *
     * @mbg.generated
     */
    private String messageType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_strategy.id
     *
     * @return the value of message_strategy.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_strategy.id
     *
     * @param id the value for message_strategy.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_strategy.limit_date
     *
     * @return the value of message_strategy.limit_date
     *
     * @mbg.generated
     */
    public String getLimitDate() {
        return limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_strategy.limit_date
     *
     * @param limitDate the value for message_strategy.limit_date
     *
     * @mbg.generated
     */
    public void setLimitDate(String limitDate) {
        this.limitDate = limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_strategy.total_count
     *
     * @return the value of message_strategy.total_count
     *
     * @mbg.generated
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_strategy.total_count
     *
     * @param totalCount the value for message_strategy.total_count
     *
     * @mbg.generated
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_strategy.sended_count
     *
     * @return the value of message_strategy.sended_count
     *
     * @mbg.generated
     */
    public Integer getSendedCount() {
        return sendedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_strategy.sended_count
     *
     * @param sendedCount the value for message_strategy.sended_count
     *
     * @mbg.generated
     */
    public void setSendedCount(Integer sendedCount) {
        this.sendedCount = sendedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_strategy.message_type
     *
     * @return the value of message_strategy.message_type
     *
     * @mbg.generated
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_strategy.message_type
     *
     * @param messageType the value for message_strategy.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }
}