package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class OnsiteRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.hunter_company_id
     *
     * @mbg.generated
     */
    private Integer hunterCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.hunter_id
     *
     * @mbg.generated
     */
    private Integer hunterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.jd_id
     *
     * @mbg.generated
     */
    private Integer jdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.recommend_record_id
     *
     * @mbg.generated
     */
    private Integer recommendRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.step
     *
     * @mbg.generated
     */
    private String step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.action_date
     *
     * @mbg.generated
     */
    private Date actionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.offer_amount
     *
     * @mbg.generated
     */
    private BigDecimal offerAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.offer_amount_unit
     *
     * @mbg.generated
     */
    private BigDecimal offerAmountUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onsite_record.onsite_type
     *
     * @mbg.generated
     */
    private String onsiteType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.hunter_company_id
     *
     * @return the value of onsite_record.hunter_company_id
     *
     * @mbg.generated
     */
    public Integer getHunterCompanyId() {
        return hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.hunter_company_id
     *
     * @param hunterCompanyId the value for onsite_record.hunter_company_id
     *
     * @mbg.generated
     */
    public void setHunterCompanyId(Integer hunterCompanyId) {
        this.hunterCompanyId = hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.hunter_id
     *
     * @return the value of onsite_record.hunter_id
     *
     * @mbg.generated
     */
    public Integer getHunterId() {
        return hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.hunter_id
     *
     * @param hunterId the value for onsite_record.hunter_id
     *
     * @mbg.generated
     */
    public void setHunterId(Integer hunterId) {
        this.hunterId = hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.company_id
     *
     * @return the value of onsite_record.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.company_id
     *
     * @param companyId the value for onsite_record.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.jd_id
     *
     * @return the value of onsite_record.jd_id
     *
     * @mbg.generated
     */
    public Integer getJdId() {
        return jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.jd_id
     *
     * @param jdId the value for onsite_record.jd_id
     *
     * @mbg.generated
     */
    public void setJdId(Integer jdId) {
        this.jdId = jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.recommend_record_id
     *
     * @return the value of onsite_record.recommend_record_id
     *
     * @mbg.generated
     */
    public Integer getRecommendRecordId() {
        return recommendRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.recommend_record_id
     *
     * @param recommendRecordId the value for onsite_record.recommend_record_id
     *
     * @mbg.generated
     */
    public void setRecommendRecordId(Integer recommendRecordId) {
        this.recommendRecordId = recommendRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.status
     *
     * @return the value of onsite_record.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.status
     *
     * @param status the value for onsite_record.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.remark
     *
     * @return the value of onsite_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.remark
     *
     * @param remark the value for onsite_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.step
     *
     * @return the value of onsite_record.step
     *
     * @mbg.generated
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.step
     *
     * @param step the value for onsite_record.step
     *
     * @mbg.generated
     */
    public void setStep(String step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.action_date
     *
     * @return the value of onsite_record.action_date
     *
     * @mbg.generated
     */
    public Date getActionDate() {
        return actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.action_date
     *
     * @param actionDate the value for onsite_record.action_date
     *
     * @mbg.generated
     */
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.offer_amount
     *
     * @return the value of onsite_record.offer_amount
     *
     * @mbg.generated
     */
    public BigDecimal getOfferAmount() {
        return offerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.offer_amount
     *
     * @param offerAmount the value for onsite_record.offer_amount
     *
     * @mbg.generated
     */
    public void setOfferAmount(BigDecimal offerAmount) {
        this.offerAmount = offerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.offer_amount_unit
     *
     * @return the value of onsite_record.offer_amount_unit
     *
     * @mbg.generated
     */
    public BigDecimal getOfferAmountUnit() {
        return offerAmountUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.offer_amount_unit
     *
     * @param offerAmountUnit the value for onsite_record.offer_amount_unit
     *
     * @mbg.generated
     */
    public void setOfferAmountUnit(BigDecimal offerAmountUnit) {
        this.offerAmountUnit = offerAmountUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onsite_record.onsite_type
     *
     * @return the value of onsite_record.onsite_type
     *
     * @mbg.generated
     */
    public String getOnsiteType() {
        return onsiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onsite_record.onsite_type
     *
     * @param onsiteType the value for onsite_record.onsite_type
     *
     * @mbg.generated
     */
    public void setOnsiteType(String onsiteType) {
        this.onsiteType = onsiteType;
    }
}