package com.model;

public class PerferenceJdIndustryFunction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perference_jd_industry_function.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perference_jd_industry_function.hunter_id
     *
     * @mbg.generated
     */
    private Integer hunterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perference_jd_industry_function.jd_industry_function_id
     *
     * @mbg.generated
     */
    private Integer jdIndustryFunctionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perference_jd_industry_function.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perference_jd_industry_function.id
     *
     * @return the value of perference_jd_industry_function.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perference_jd_industry_function.id
     *
     * @param id the value for perference_jd_industry_function.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perference_jd_industry_function.hunter_id
     *
     * @return the value of perference_jd_industry_function.hunter_id
     *
     * @mbg.generated
     */
    public Integer getHunterId() {
        return hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perference_jd_industry_function.hunter_id
     *
     * @param hunterId the value for perference_jd_industry_function.hunter_id
     *
     * @mbg.generated
     */
    public void setHunterId(Integer hunterId) {
        this.hunterId = hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perference_jd_industry_function.jd_industry_function_id
     *
     * @return the value of perference_jd_industry_function.jd_industry_function_id
     *
     * @mbg.generated
     */
    public Integer getJdIndustryFunctionId() {
        return jdIndustryFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perference_jd_industry_function.jd_industry_function_id
     *
     * @param jdIndustryFunctionId the value for perference_jd_industry_function.jd_industry_function_id
     *
     * @mbg.generated
     */
    public void setJdIndustryFunctionId(Integer jdIndustryFunctionId) {
        this.jdIndustryFunctionId = jdIndustryFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perference_jd_industry_function.name
     *
     * @return the value of perference_jd_industry_function.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perference_jd_industry_function.name
     *
     * @param name the value for perference_jd_industry_function.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }
}