package com.model;

import java.math.BigDecimal;

public class PtAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_account.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_account.is_valid
     *
     * @mbg.generated
     */
    private String isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_account.id
     *
     * @return the value of pt_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_account.id
     *
     * @param id the value for pt_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_account.amount
     *
     * @return the value of pt_account.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_account.amount
     *
     * @param amount the value for pt_account.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_account.is_valid
     *
     * @return the value of pt_account.is_valid
     *
     * @mbg.generated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_account.is_valid
     *
     * @param isValid the value for pt_account.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }
}