package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class PtCollectionRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.hunter_company_id
     *
     * @mbg.generated
     */
    private Integer hunterCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.hunter_id
     *
     * @mbg.generated
     */
    private Integer hunterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.jd_id
     *
     * @mbg.generated
     */
    private Integer jdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.recommend_record_id
     *
     * @mbg.generated
     */
    private Integer recommendRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.collection_plan_id
     *
     * @mbg.generated
     */
    private Integer collectionPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.collected_date
     *
     * @mbg.generated
     */
    private Date collectedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.collected_amount
     *
     * @mbg.generated
     */
    private BigDecimal collectedAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.series_number
     *
     * @mbg.generated
     */
    private String seriesNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_collection_record.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.id
     *
     * @return the value of pt_collection_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.id
     *
     * @param id the value for pt_collection_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.hunter_company_id
     *
     * @return the value of pt_collection_record.hunter_company_id
     *
     * @mbg.generated
     */
    public Integer getHunterCompanyId() {
        return hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.hunter_company_id
     *
     * @param hunterCompanyId the value for pt_collection_record.hunter_company_id
     *
     * @mbg.generated
     */
    public void setHunterCompanyId(Integer hunterCompanyId) {
        this.hunterCompanyId = hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.hunter_id
     *
     * @return the value of pt_collection_record.hunter_id
     *
     * @mbg.generated
     */
    public Integer getHunterId() {
        return hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.hunter_id
     *
     * @param hunterId the value for pt_collection_record.hunter_id
     *
     * @mbg.generated
     */
    public void setHunterId(Integer hunterId) {
        this.hunterId = hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.company_id
     *
     * @return the value of pt_collection_record.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.company_id
     *
     * @param companyId the value for pt_collection_record.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.jd_id
     *
     * @return the value of pt_collection_record.jd_id
     *
     * @mbg.generated
     */
    public Integer getJdId() {
        return jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.jd_id
     *
     * @param jdId the value for pt_collection_record.jd_id
     *
     * @mbg.generated
     */
    public void setJdId(Integer jdId) {
        this.jdId = jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.recommend_record_id
     *
     * @return the value of pt_collection_record.recommend_record_id
     *
     * @mbg.generated
     */
    public Integer getRecommendRecordId() {
        return recommendRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.recommend_record_id
     *
     * @param recommendRecordId the value for pt_collection_record.recommend_record_id
     *
     * @mbg.generated
     */
    public void setRecommendRecordId(Integer recommendRecordId) {
        this.recommendRecordId = recommendRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.collection_plan_id
     *
     * @return the value of pt_collection_record.collection_plan_id
     *
     * @mbg.generated
     */
    public Integer getCollectionPlanId() {
        return collectionPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.collection_plan_id
     *
     * @param collectionPlanId the value for pt_collection_record.collection_plan_id
     *
     * @mbg.generated
     */
    public void setCollectionPlanId(Integer collectionPlanId) {
        this.collectionPlanId = collectionPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.remark
     *
     * @return the value of pt_collection_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.remark
     *
     * @param remark the value for pt_collection_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.collected_date
     *
     * @return the value of pt_collection_record.collected_date
     *
     * @mbg.generated
     */
    public Date getCollectedDate() {
        return collectedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.collected_date
     *
     * @param collectedDate the value for pt_collection_record.collected_date
     *
     * @mbg.generated
     */
    public void setCollectedDate(Date collectedDate) {
        this.collectedDate = collectedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.collected_amount
     *
     * @return the value of pt_collection_record.collected_amount
     *
     * @mbg.generated
     */
    public BigDecimal getCollectedAmount() {
        return collectedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.collected_amount
     *
     * @param collectedAmount the value for pt_collection_record.collected_amount
     *
     * @mbg.generated
     */
    public void setCollectedAmount(BigDecimal collectedAmount) {
        this.collectedAmount = collectedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.series_number
     *
     * @return the value of pt_collection_record.series_number
     *
     * @mbg.generated
     */
    public String getSeriesNumber() {
        return seriesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.series_number
     *
     * @param seriesNumber the value for pt_collection_record.series_number
     *
     * @mbg.generated
     */
    public void setSeriesNumber(String seriesNumber) {
        this.seriesNumber = seriesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_collection_record.status
     *
     * @return the value of pt_collection_record.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_collection_record.status
     *
     * @param status the value for pt_collection_record.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}