package com.model;

public class RecommendRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.hunter_company_id
     *
     * @mbg.generated
     */
    private Integer hunterCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.hunter_id
     *
     * @mbg.generated
     */
    private Integer hunterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.jd_id
     *
     * @mbg.generated
     */
    private Integer jdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.candidate_name
     *
     * @mbg.generated
     */
    private String candidateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.expect_salary
     *
     * @mbg.generated
     */
    private Integer expectSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.educational
     *
     * @mbg.generated
     */
    private String educational;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.CV_url
     *
     * @mbg.generated
     */
    private String cvUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.CV_location_type
     *
     * @mbg.generated
     */
    private String cvLocationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.recommend_desc
     *
     * @mbg.generated
     */
    private String recommendDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.workyear
     *
     * @mbg.generated
     */
    private Integer workyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend_record.paid_status
     *
     * @mbg.generated
     */
    private String paidStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.id
     *
     * @return the value of recommend_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.id
     *
     * @param id the value for recommend_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.hunter_company_id
     *
     * @return the value of recommend_record.hunter_company_id
     *
     * @mbg.generated
     */
    public Integer getHunterCompanyId() {
        return hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.hunter_company_id
     *
     * @param hunterCompanyId the value for recommend_record.hunter_company_id
     *
     * @mbg.generated
     */
    public void setHunterCompanyId(Integer hunterCompanyId) {
        this.hunterCompanyId = hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.hunter_id
     *
     * @return the value of recommend_record.hunter_id
     *
     * @mbg.generated
     */
    public Integer getHunterId() {
        return hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.hunter_id
     *
     * @param hunterId the value for recommend_record.hunter_id
     *
     * @mbg.generated
     */
    public void setHunterId(Integer hunterId) {
        this.hunterId = hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.company_id
     *
     * @return the value of recommend_record.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.company_id
     *
     * @param companyId the value for recommend_record.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.jd_id
     *
     * @return the value of recommend_record.jd_id
     *
     * @mbg.generated
     */
    public Integer getJdId() {
        return jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.jd_id
     *
     * @param jdId the value for recommend_record.jd_id
     *
     * @mbg.generated
     */
    public void setJdId(Integer jdId) {
        this.jdId = jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.candidate_name
     *
     * @return the value of recommend_record.candidate_name
     *
     * @mbg.generated
     */
    public String getCandidateName() {
        return candidateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.candidate_name
     *
     * @param candidateName the value for recommend_record.candidate_name
     *
     * @mbg.generated
     */
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.expect_salary
     *
     * @return the value of recommend_record.expect_salary
     *
     * @mbg.generated
     */
    public Integer getExpectSalary() {
        return expectSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.expect_salary
     *
     * @param expectSalary the value for recommend_record.expect_salary
     *
     * @mbg.generated
     */
    public void setExpectSalary(Integer expectSalary) {
        this.expectSalary = expectSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.age
     *
     * @return the value of recommend_record.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.age
     *
     * @param age the value for recommend_record.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.educational
     *
     * @return the value of recommend_record.educational
     *
     * @mbg.generated
     */
    public String getEducational() {
        return educational;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.educational
     *
     * @param educational the value for recommend_record.educational
     *
     * @mbg.generated
     */
    public void setEducational(String educational) {
        this.educational = educational;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.company_name
     *
     * @return the value of recommend_record.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.company_name
     *
     * @param companyName the value for recommend_record.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.tel
     *
     * @return the value of recommend_record.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.tel
     *
     * @param tel the value for recommend_record.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.mail
     *
     * @return the value of recommend_record.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.mail
     *
     * @param mail the value for recommend_record.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.title
     *
     * @return the value of recommend_record.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.title
     *
     * @param title the value for recommend_record.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.department
     *
     * @return the value of recommend_record.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.department
     *
     * @param department the value for recommend_record.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.CV_url
     *
     * @return the value of recommend_record.CV_url
     *
     * @mbg.generated
     */
    public String getCvUrl() {
        return cvUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.CV_url
     *
     * @param cvUrl the value for recommend_record.CV_url
     *
     * @mbg.generated
     */
    public void setCvUrl(String cvUrl) {
        this.cvUrl = cvUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.CV_location_type
     *
     * @return the value of recommend_record.CV_location_type
     *
     * @mbg.generated
     */
    public String getCvLocationType() {
        return cvLocationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.CV_location_type
     *
     * @param cvLocationType the value for recommend_record.CV_location_type
     *
     * @mbg.generated
     */
    public void setCvLocationType(String cvLocationType) {
        this.cvLocationType = cvLocationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.recommend_desc
     *
     * @return the value of recommend_record.recommend_desc
     *
     * @mbg.generated
     */
    public String getRecommendDesc() {
        return recommendDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.recommend_desc
     *
     * @param recommendDesc the value for recommend_record.recommend_desc
     *
     * @mbg.generated
     */
    public void setRecommendDesc(String recommendDesc) {
        this.recommendDesc = recommendDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.workyear
     *
     * @return the value of recommend_record.workyear
     *
     * @mbg.generated
     */
    public Integer getWorkyear() {
        return workyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.workyear
     *
     * @param workyear the value for recommend_record.workyear
     *
     * @mbg.generated
     */
    public void setWorkyear(Integer workyear) {
        this.workyear = workyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.status
     *
     * @return the value of recommend_record.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.status
     *
     * @param status the value for recommend_record.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.remark
     *
     * @return the value of recommend_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.remark
     *
     * @param remark the value for recommend_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend_record.paid_status
     *
     * @return the value of recommend_record.paid_status
     *
     * @mbg.generated
     */
    public String getPaidStatus() {
        return paidStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend_record.paid_status
     *
     * @param paidStatus the value for recommend_record.paid_status
     *
     * @mbg.generated
     */
    public void setPaidStatus(String paidStatus) {
        this.paidStatus = paidStatus;
    }
}