package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class RepaymentPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.hunter_company_id
     *
     * @mbg.generated
     */
    private Integer hunterCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.hunter_id
     *
     * @mbg.generated
     */
    private Integer hunterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.jd_id
     *
     * @mbg.generated
     */
    private Integer jdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.recommend_record_id
     *
     * @mbg.generated
     */
    private Integer recommendRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.expected_date
     *
     * @mbg.generated
     */
    private Date expectedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_plan.paid_amount
     *
     * @mbg.generated
     */
    private BigDecimal paidAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.id
     *
     * @return the value of repayment_plan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.id
     *
     * @param id the value for repayment_plan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.hunter_company_id
     *
     * @return the value of repayment_plan.hunter_company_id
     *
     * @mbg.generated
     */
    public Integer getHunterCompanyId() {
        return hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.hunter_company_id
     *
     * @param hunterCompanyId the value for repayment_plan.hunter_company_id
     *
     * @mbg.generated
     */
    public void setHunterCompanyId(Integer hunterCompanyId) {
        this.hunterCompanyId = hunterCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.hunter_id
     *
     * @return the value of repayment_plan.hunter_id
     *
     * @mbg.generated
     */
    public Integer getHunterId() {
        return hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.hunter_id
     *
     * @param hunterId the value for repayment_plan.hunter_id
     *
     * @mbg.generated
     */
    public void setHunterId(Integer hunterId) {
        this.hunterId = hunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.company_id
     *
     * @return the value of repayment_plan.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.company_id
     *
     * @param companyId the value for repayment_plan.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.jd_id
     *
     * @return the value of repayment_plan.jd_id
     *
     * @mbg.generated
     */
    public Integer getJdId() {
        return jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.jd_id
     *
     * @param jdId the value for repayment_plan.jd_id
     *
     * @mbg.generated
     */
    public void setJdId(Integer jdId) {
        this.jdId = jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.recommend_record_id
     *
     * @return the value of repayment_plan.recommend_record_id
     *
     * @mbg.generated
     */
    public Integer getRecommendRecordId() {
        return recommendRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.recommend_record_id
     *
     * @param recommendRecordId the value for repayment_plan.recommend_record_id
     *
     * @mbg.generated
     */
    public void setRecommendRecordId(Integer recommendRecordId) {
        this.recommendRecordId = recommendRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.status
     *
     * @return the value of repayment_plan.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.status
     *
     * @param status the value for repayment_plan.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.remark
     *
     * @return the value of repayment_plan.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.remark
     *
     * @param remark the value for repayment_plan.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.version
     *
     * @return the value of repayment_plan.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.version
     *
     * @param version the value for repayment_plan.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.expected_date
     *
     * @return the value of repayment_plan.expected_date
     *
     * @mbg.generated
     */
    public Date getExpectedDate() {
        return expectedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.expected_date
     *
     * @param expectedDate the value for repayment_plan.expected_date
     *
     * @mbg.generated
     */
    public void setExpectedDate(Date expectedDate) {
        this.expectedDate = expectedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.amount
     *
     * @return the value of repayment_plan.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.amount
     *
     * @param amount the value for repayment_plan.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_plan.paid_amount
     *
     * @return the value of repayment_plan.paid_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_plan.paid_amount
     *
     * @param paidAmount the value for repayment_plan.paid_amount
     *
     * @mbg.generated
     */
    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }
}